"""
Generates tb_pinch_rotation.v — a Verilog testbench that exercises
gesture_classifier on synthetic pinch-rotation frames. The frames are built
in Python using the same normalisation as landmark_capture.py so what the
testbench feeds the classifier is bit-exact to what real hardware will see.

The testbench asserts on gesture_id values directly (no waveform eyeballing):
 * a HELD block of N frames with no rotation must never emit PINCH_CW/ACW
 * a SLOW_CW block must emit at least one PINCH_CW and no PINCH_ACW
 * a SLOW_ACW block must emit at least one PINCH_ACW and no PINCH_CW
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from verify_pinch_rotation import synth_pinch_frame, normalise_landmarks


def pack_frame_hex(lm_px):
    x16, y16 = normalise_landmarks(lm_px)
    # landmark N occupies bits [N*16 +: 16]; hex literal MSB-first.
    x_bits = 0
    y_bits = 0
    for i in range(21):
        x_bits |= (x16[i] & 0xFFFF) << (i * 16)
        y_bits |= (y16[i] & 0xFFFF) << (i * 16)
    return f"336'h{x_bits:084x}", f"336'h{y_bits:084x}"


def build_block(label, angles):
    """Return (verilog_snippet, num_frames) for a labelled block of frames."""
    lines = [f'        // ---- {label} ----',
             f'        label = "{label}";']
    for ang in angles:
        lm = synth_pinch_frame(ang)
        xh, yh = pack_frame_hex(lm)
        lines.append(f'        send_frame({xh}, {yh});')
    return '\n'.join(lines), len(angles)


def main():
    # Angles are continuous across block boundaries so there is no
    # discontinuous jump that would look like a rotation to the classifier.
    held_start    = 45.0
    held_angles   = [held_start] * 30                                          # stays at 45
    cw_start      = held_angles[-1]
    cw_angles     = [cw_start + 2.0 * (i + 1) for i in range(30)]              # 47..105
    held2_start   = cw_angles[-1]
    held2_angles  = [held2_start] * 10                                         # stays at 105
    acw_start     = held2_angles[-1]
    acw_angles    = [acw_start - 2.0 * (i + 1) for i in range(30)]             # 103..45

    blocks = []
    for label, angles in [
        ('HELD',     held_angles),
        ('SLOW_CW',  cw_angles),
        ('HELD2',    held2_angles),
        ('SLOW_ACW', acw_angles),
    ]:
        snippet, n = build_block(label, angles)
        blocks.append((label, snippet, n))

    body = '\n\n'.join(s for _, s, _ in blocks)

    tb = f'''`timescale 1ns/1ps

// Auto-generated by gen_pinch_rotation_tb.py — do not edit by hand.
// Exercises the dynamic pinch-rotation path of gesture_classifier using
// synthetic frames whose 16-bit landmarks are the exact values produced by
// landmark_capture.py's normalisation for each pose.

module tb_pinch_rotation;

    reg         clk;
    reg         rst;
    reg         valid_in;
    reg [335:0] x;
    reg [335:0] y;

    wire [2:0]  gesture_id;
    wire        valid_out;

    // Per-label emission counters
    reg [31:0] cnt_pinch, cnt_cw, cnt_acw, cnt_unknown, cnt_other;
    reg [8*10-1:0] label;   // up to 10-char label

    gesture_classifier dut (
        .clk        (clk),
        .rst        (rst),
        .valid_in   (valid_in),
        .x          (x),
        .y          (y),
        .gesture_id (gesture_id),
        .valid_out  (valid_out)
    );

    initial clk = 0;
    always #10 clk = ~clk; // 50 MHz

    task send_frame;
        input [335:0] lx;
        input [335:0] ly;
        begin
            x = lx;
            y = ly;
            valid_in = 1;
            repeat(20) @(posedge clk); // let pipeline run (angle calc latency)
            valid_in = 0;
            repeat(50) @(posedge clk); // gap
        end
    endtask

    task reset_counts;
        begin
            cnt_pinch   = 0;
            cnt_cw      = 0;
            cnt_acw     = 0;
            cnt_unknown = 0;
            cnt_other   = 0;
        end
    endtask

    task dump_counts;
        begin
            $display("[%0s] pinch=%0d cw=%0d acw=%0d unknown=%0d other=%0d",
                     label, cnt_pinch, cnt_cw, cnt_acw, cnt_unknown, cnt_other);
        end
    endtask

    // ---- pass/fail tracking ----
    integer fail_count;
    reg [31:0] h_pinch, h_cw, h_acw, h_unk, h_oth;
    reg [31:0] cw_pinch, cw_cw, cw_acw, cw_unk, cw_oth;
    reg [31:0] ac_pinch, ac_cw, ac_acw, ac_unk, ac_oth;

    initial begin
        $dumpfile("tb_pinch_rotation.vcd");
        $dumpvars(0, tb_pinch_rotation);

        rst = 1;
        valid_in = 0;
        x = 0;
        y = 0;
        label = "INIT";
        reset_counts();
        fail_count = 0;

        repeat(5) @(posedge clk);
        rst = 0;
        repeat(2) @(posedge clk);

{body}

        // Capture ACW counts (last block)
        ac_pinch = cnt_pinch;
        ac_cw    = cnt_cw;
        ac_acw   = cnt_acw;
        ac_unk   = cnt_unknown;
        ac_oth   = cnt_other;

        // ---- Assertions ----
        $display("\\n=== RESULTS ===");
        $display("HELD     : pinch=%0d cw=%0d acw=%0d",  h_pinch,  h_cw,  h_acw);
        $display("SLOW_CW  : pinch=%0d cw=%0d acw=%0d", cw_pinch, cw_cw, cw_acw);
        $display("SLOW_ACW : pinch=%0d cw=%0d acw=%0d", ac_pinch, ac_cw, ac_acw);

        if (h_cw != 0 || h_acw != 0) begin
            $display("FAIL: HELD fired rotation events (cw=%0d acw=%0d) — accumulator drift",
                     h_cw, h_acw);
            fail_count = fail_count + 1;
        end
        if (cw_cw == 0) begin
            $display("FAIL: SLOW_CW did not emit any PINCH_CW");
            fail_count = fail_count + 1;
        end
        if (cw_acw != 0) begin
            $display("FAIL: SLOW_CW emitted PINCH_ACW (wrong direction)");
            fail_count = fail_count + 1;
        end
        if (ac_acw == 0) begin
            $display("FAIL: SLOW_ACW did not emit any PINCH_ACW");
            fail_count = fail_count + 1;
        end
        if (ac_cw != 0) begin
            $display("FAIL: SLOW_ACW emitted PINCH_CW (wrong direction)");
            fail_count = fail_count + 1;
        end

        if (fail_count == 0)
            $display("\\nALL ASSERTIONS PASSED");
        else
            $display("\\n%0d ASSERTION(S) FAILED", fail_count);

        repeat(10) @(posedge clk);
        $finish;
    end

    // Count emissions per block and snapshot when label changes.
    reg [8*10-1:0] prev_label;
    initial prev_label = "INIT";

    always @(posedge clk) begin
        if (label !== prev_label) begin
            // Snapshot the previous block's counts into the appropriate bank.
            case (prev_label)
                "HELD"    : begin h_pinch <= cnt_pinch; h_cw <= cnt_cw; h_acw <= cnt_acw; h_unk <= cnt_unknown; h_oth <= cnt_other; end
                "SLOW_CW" : begin cw_pinch <= cnt_pinch; cw_cw <= cnt_cw; cw_acw <= cnt_acw; cw_unk <= cnt_unknown; cw_oth <= cnt_other; end
                default   : ;
            endcase
            reset_counts();
            prev_label <= label;
        end

        if (valid_out) begin
            case (gesture_id)
                3'b000: cnt_pinch   <= cnt_pinch + 1;
                3'b100: cnt_unknown <= cnt_unknown + 1;
                3'b101: cnt_cw      <= cnt_cw + 1;
                3'b110: cnt_acw     <= cnt_acw + 1;
                default: cnt_other  <= cnt_other + 1;
            endcase
        end
    end

endmodule
'''

    out = os.path.join(HERE, 'tb_pinch_rotation.v')
    with open(out, 'w') as f:
        f.write(tb)
    print(f"Wrote {out}  ({sum(n for _,_,n in blocks)} frames across {len(blocks)} blocks)")


if __name__ == '__main__':
    main()
